version: '3.7'
services:
  kalilinux:
    hostname: kalilinux.lab
    build:
      context: ./
      dockerfile: Dockerfile
    image: 'emileastih/kalilinux:1.0'
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - 0.0.0.0:8080:8080
    working_dir: /root
    environment:
      - SHELL=/bin/bash
      - PASSWORD=kalilinux
    entrypoint: ["/bin/bash", "/startup.sh"]